### ISSUE TITLE
Artificial Neural Net - Multilayer should use tasks, not glue strings together for `runresult`

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#10]
see http://stackoverflow.com/questions/25515311/puzzled-by-netlogo-syntax

**Comment by heychia** [comment]
Hi! I came here from the question linked by Seth above and saw that the said issue has been closed. Does it mean that there is an update example code for the Multilayer ANN model available? If so, may I ask from where I could download it, please? Thanks!
