### ISSUE TITLE
Test model compilation using NetLogo-Headless

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#101]
Various branches of JVM NetLogo have [their own](https://github.com/NetLogo/NetLogo/blob/5.x/src/test/org/nlogo/headless/TestCompileAll.scala) tests for model compilation. And it makes sense to keep those tests there, because they act as regression tests for NetLogo: if something changes in NetLogo and compilation breaks as a result, we want to know right away.

But... those tests only run when NetLogo itself changes, and the `models` submodule pointer is not always up to date in the NetLogo repo.

If a compile time error sneaks into a model that is pushed to the `models` repo, I want to know right away. Hence the current issue.

Why [Headless](https://github.com/NetLogo/NetLogo-Headless) instead of 5.x?

- 5.x is still in scala 2.9.3. The `models` test are in scala 2.11.6, so the 5.x jar is binary incompatible.
- Headless should be much more pleasant to work with.
- Library models should compile in Headless anyway. If there are exceptions, they can be added to the tests.
- This is just an early warning system. `TestCompileAll` will keep running in the 5.x branch.

**Comment by frankduncan** [comment]
3d will probably be a problem

**Comment by frankduncan** [comment]
If you'd like to work off of a 5.x deployable on java 8, you can use the jar located at

http://ccl.northwestern.edu/devel/NetLogo-5.3-17964bb.jar

**Comment by nicolaspayette** [comment]
Hmm... thanks, Frank! I just might do that!

**Comment by nicolaspayette** [comment]
Quick report:

- I used the 5.3 jar provided by Frank;
- 3D models and models using extensions are excluded from the tests. It would be nice if we could find a way to include them, but it's no big deal since they're covered in the main repos' tests.
