### ISSUE TITLE
Using singular breed name as parameter name shouldn't be allowed

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#106]
Because of https://github.com/NetLogo/Tortoise/issues/123.

**Bird Breeders HubNet** (`which-player-bird-or-egg-is-this?` procedure) is the only currently known case. 

I'll see if I can write a test to catch this.

**Comment by arthurhjorth** [comment]
This may be a stupid question, but isn't this something that simply shouldn't be allowed by the compiler or interpreter (I'm still not sure what the difference is)?

Why isn't the singular name simply registered as a variable name like the plural name is? Would this be a lot of work?

**Comment by nicolaspayette** [comment]
> isn't this something that simply shouldn't be allowed by the compiler

You're right: it shouldn't be allowed. In https://github.com/NetLogo/Tortoise/issues/123, @SethTisue  described it as a "loophole" that got closed in NLW and in what is now the 6.x branch. It's just unlikely that the fix is ever ported back to 5.x.

**Comment by nicolaspayette** [comment]
Test results:

~~~
[info] - Singular breed names should not be used as args/local names *** FAILED ***
[info]   "/home/travis/build/NetLogo/models/Curricular Models/BEAGLE Evolution/HubNet Activities/Bird Breeders HubNet.nlogo":
[info]     BIRD in WHICH-PLAYER-BIRD-OR-EGG-IS-THIS?
[info]   "/home/travis/build/NetLogo/models/HubNet Activities/Root Beer Game HubNet.nlogo":
[info]     TEAM in ADD-STUDENT-TO
[info]   "/home/travis/build/NetLogo/models/HubNet Activities/Unverified/Function HubNet.nlogo":
[info]     STUDENT in EDIT-STUDENT-EQUATION
[info]     -- (TestModels.scala:16)
[info] - All breeds should have singular names *** FAILED ***
[info]   "/home/travis/build/NetLogo/models/Curricular Models/ProbLab/4 Block Stalagmites.nlogo":  
[info]   SAMPLE-ORGANIZERS
[info]     -- (TestModels.scala:16)
~~~

(While I was at it, I also added a test for https://github.com/NetLogo/NetLogo/issues/709)
