### ISSUE TITLE
Most Connected Chemistry models have two calls to `reset-ticks` in `setup`

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#116]
One at the top of `setup`, just after `clear-all`, and one at the end. The top ones should be removed...

In fact, it would make sense to write a test for multiple usages of `reset-ticks`. If there turns out to be legitimate cases (which I doubt) they can be added as exceptions.

**Comment by Idloj** [comment]
Will a test for multiple `reset-ticks` in the same procedure be sufficient?

**Comment by nicolaspayette** [comment]
That's what I'm hoping for.

**Comment by Idloj** [comment]
sorry for asking this, but can you give me some kind of instructions for how to write such a test?
