### ISSUE TITLE
BeeSmart 2nd model

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/models#135]
@toxy100 how is your checkout going? did you make the revisions that Nicolas suggested? we're aiming to release today or tomorrow.

**Comment by nicolaspayette** [comment]
Duplicate of #124.

**Comment by arthurhjorth** [comment]
Whoops, I am not sure how, but I dup... Nicolas beat me to it. THanks.

**Comment by nicolaspayette** [comment]
:-)
