### ISSUE TITLE
Some Connected Chemistry models have strange pseudo-Monitors

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/models#136]
**Affected Models**:
  * Connected Chemistry 2
  * Connected Chemistry 4
  * Connected Chemistry 5
  * Connected Chemistry 6

**The Problem**:

These models display a `pressure` value that tries to be a Monitor, but it's actually an Output containing a bunch of values that you can scroll back through. It looks only slightly weird in JVM NetLogo, but it looks fairly crappy in NLW, with the correspondingly label looking fairly misplaced, some of the scrollback text wrongly being visible, the text flickering a lot from being updated much more than once per tick, and the scrollbar standing out a lot more.  Overall, I think it looks very silly in NetLogo Web, and I think that, if it can just be done as a plain Monitor, it would be for the best for everyone.

[Here](http://netlogoweb.org/launch#http://netlogoweb.org/assets/modelslib/Curricular%20Models/Connected%20Chemistry/Connected%20Chemistry%202%20Changing%20Pressure.nlogo) is a link to CC2 in NLW, which demonstrates the problem.

**Comment by SethTisue** [comment]
at the time, the CC folks (Michael N?) considered this pedagogically important — I think the “being updated much more than once per tick” was actually strongly desired — only vague memories though

**Comment by nicolaspayette** [comment]
> at the time, the CC folks (Michael N?) considered this pedagogically important

@mnovakccl, is that still the case? I'd be grateful if you could elaborate on this.

> I think the “being updated much more than once per tick” was actually strongly desired

Good to know! We'll keep that in mind if/when we make the change.

**Comment by mnovakccl** [comment]
Yes, it was for pedagogical reasons.  I think keeping the model in the
state it was in (for that reason) to represent what was in it, when we
conducted the research in the classroom for ConnectedChemistry is important.

On Mon, Oct 5, 2015 at 12:49 PM, Nicolas Payette <notifications@github.com>
wrote:

> at the time, the CC folks (Michael N?) considered this pedagogically
> important
>
> @mnovakccl <https://github.com/mnovakccl>, is that still the case? I'd be
> grateful if you could elaborate on this.
>
> I think the “being updated much more than once per tick” was actually
> strongly desired
>
> Good to know! We'll keep that in mind if/when we make the change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetLogo/models/issues/136#issuecomment-145611873>.
>



-- 
------------------------------------------------------------
Michael Novak, Instructor and
Instructional Materials Designer
Center for Connected Learning and Computer-Based Modeling
School of Education and Social Policy
Northwestern University
219 Annenberg Hall, 2120 N Campus Drive, Evanston IL 60208

**Comment by nicolaspayette** [comment]
Thanks for your answer @mnovakccl! I'm willing to close the issue and leave the models as they are, but I would really like it if you could be more explicit about the reasons why **Pressure** is an output instead of a monitor. A few things still bother me:

- A real monitor could be updated just as often as an output.
- Each model's info tab refers to **Pressure** as a _monitor_, which is technically not true.
- It doesn't look good on Linux either:

    ![cc2](https://cloud.githubusercontent.com/assets/908754/11100728/ea35c944-8880-11e5-8f12-6a9459d13cfd.png)

(That's hard to fix: if I make it look good on Linux, it won't look good on Mac/Windows anymore. Output widgets are just not designed to be one-line high.)

**Comment by mnovakccl** [comment]
Hi Nicolas,

In the old days, I think that the number monitor didn't update fast
enough.  That is the only reason I can recall using it.  So if the monitor
now updates continuously or on every tick, then we can replace the output
widget with a monitor.

---MIchael

On Wed, Nov 11, 2015 at 1:52 PM, Nicolas Payette <notifications@github.com>
wrote:

> Thanks for your answer @mnovakccl <https://github.com/mnovakccl>! I'm
> willing to close the issue and leave the models as they are, but I would
> really like it if you could be more explicit about the reasons why
> *Pressure* is an output instead of a monitor. A few things still bother
> me:
>
>    - A real monitor could be updated just as often as an output.
>    - Each model's info tab refers to *Pressure* as a *monitor*, which is
>    technically not true.
>    -
>
>    It doesn't look good on Linux either:
>
>    [image: cc2]
>    <https://cloud.githubusercontent.com/assets/908754/11100728/ea35c944-8880-11e5-8f12-6a9459d13cfd.png>
>
> (That's hard to fix: if I make it look good on Linux, it won't look good
> on Mac/Windows anymore. Output widgets are just not designed to be one-line
> high.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetLogo/models/issues/136#issuecomment-155892526>.
>



-- 
------------------------------------------------------------
Michael Novak, Instructor and
Instructional Materials Designer
Center for Connected Learning and Computer-Based Modeling
School of Education and Social Policy
Northwestern University
219 Annenberg Hall, 2120 N Campus Drive, Evanston IL 60208

**Comment by nicolaspayette** [comment]
@mnovakccl, did you get a chance to look at [the side-by-side comparison](https://raw.githubusercontent.com/NetLogo/models/2638bab584478f43a701974ccbda81dd18538591/Curricular%20Models/Connected%20Chemistry/Connected%20Chemistry%202%20Changing%20Pressure.nlogo)? At this point, I'd say that the choice is yours: unless you tell me that the monitors are fast enough, I'll just close the issue and leave the models as they are. (And maybe revisit if https://github.com/NetLogo/NetLogo/issues/663 is ever addressed.)

**Comment by mnovakccl** [comment]
I did look at it.   I think we need to keep the older faster output update method, because they were put in for a reason related to a learning goal we had designed into the materials on fluctuation and stability.   The research from testing the materials (eg papers) may make reference to it.

**Comment by nicolaspayette** [comment]
All right, thanks @mnovakccl! Closing.
