### ISSUE TITLE
Pac-Man Level Editor: runtime error when trying to place ghost from loaded level

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#150]
```
ASK expected input to be an agent or agentset but got NOBODY instead.
error while observer running ASK
  called by procedure PLACE-GHOST
  called by procedure DRAW
  called by Button 'Use Tool'
```

The `place-ghost` procedure expects ghost to have `who` numbers 1, 2, 3 and 4, but the `load-level` procedure (using `import-world`) doesn't guarantee that this will be the case. Moral of the story: using `who` numbers is pretty much always a bad idea.

**Comment by SethTisue** [comment]
![PHP](https://pbs.twimg.com/profile_images/552595603687874561/Yd-jBihK.jpeg) fix this critical bug in Pac-Man Level Editor right away or else!!!

**Comment by SethTisue** [comment]
![](http://www.wellhappypeaceful.com/wp-content/uploads/2012/04/buddha.jpg)

**Comment by nicolaspayette** [comment]
:-)
