### ISSUE TITLE
Artificial Neural Net - Multilayer: doc improvements?

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#158]
on Gitter @mrn-aglic suggested:

@mrn-aglic:
> as far as I can see in the info tab on "How it works", the backward pass of the algorithm isn't even mentioned... Perhaps the idea should be written down. And in the code, it would be helpful that it is noted that (activation) * (1 - activation) is a way to express the derivative of the sigmoid function.... if the user tries to use a different activation function, they would need to change this as well...

**Comment by qiemem** [comment]
Currently, it says:

> The network uses a back-propagation algorithm to pass error back from the output node and uses this error to update the weights along each link.

but that could definitely be expanded.

**Comment by mrn-aglic** [comment]
@qiemem A short description of how this error is passed back to the hidden layer might be useful.

**Comment by SethTisue** [comment]
@mrn-aglic would you like submit a PR with proposed wording? you may know more about the model than any of us do, at this point

**Comment by mrn-aglic** [comment]
@SethTisue I can try and write something down over the weekend.

**Comment by nicolaspayette** [comment]
Solved #162, #163.
