### ISSUE TITLE
Rumor Mill documentation bug

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#188]
The info tab states "SUCCESSIVE RATIOS - plots the percentage of new people who are hearing the rumor at each time step." and yet the code is

    ifelse previous-clique = 0 [ plot 1 ] [ plot clique / previous-clique ]

which is the ratio of those who heard the rumor to the number on the previous tick.

**Comment by nicolaspayette** [comment]
Thanks for reporting! I'll see to it!
