### ISSUE TITLE
Test that plotting code is in plots

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#198]
Once in while, I come across a model that still has "old style" plotting in code in the main code tab. There should be a test to detect those.

**Comment by OASCCL** [comment]
We have not decided to convert all models to new-style plotting.
When we last discussed it a few years ago, we decided to hold off.

—Uri

Uri Wilensky

**Comment by nicolaspayette** [comment]
What prompted me to open this issue is looking at **Urban Suite - Awareness** for #196:

https://github.com/NetLogo/models/blob/master/Curricular%20Models/Urban%20Suite/Urban%20Suite%20-%20Awareness.nlogo#L96

In that particular case, I see no reason why the code should not be in the plots. But if other models are better off with plotting code in the main code tab, we don't have to convert them.

**Comment by SethTisue** [comment]
> We have not decided to convert all models to new-style plotting.
> When we last discussed it a few years ago, we decided to hold off.

There is a divide here between Sample Models and Code Examples on the one hand, and Curricular Models on the other hand.

With perhaps a few exceptions on both sides, all of the former were converted a long time ago, but many of the latter were not.
