### ISSUE TITLE
Fireflies turtles-own threshold is identical to flash-length parameter

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#205]
It could be replaced everywhere by flash-length (which the Info tab refers to "a firefly will reset its clock to the FLASH-LENGTH tick") and eliminated.

The current code means that flash-length can't be changed while running. Is that desirable?

Also why is the word "tick" in "a firefly will reset its clock to the FLASH-LENGTH tick"?

FLASHES-TO-RESTART in Info Tab while it is FLASHES-TO-RESET in the code.

I find the description of STRATEGY in the Info Tab hard to understand.

**Comment by nicolaspayette** [comment]
> Also why is the word "tick" in "a firefly will reset its clock to the FLASH-LENGTH tick"?

That either a typo or just a weird turn of phrase. In any case, I got rid of it.

> FLASHES-TO-RESTART in Info Tab while it is FLASHES-TO-RESET in the code.

Good catch! Fixed.

> I find the description of STRATEGY in the Info Tab hard to understand.

Me too. I'll see if I can improve it.

And now, the big one:

> The current code means that flash-length can't be changed while running. Is that desirable?

It seems like someone along the way thought it was. The info tab explicitly says:

> All settings (except SHOW-DARK-FIREFLIES) must be set before pressing the SETUP button. Changes to the sliders (except SHOW-DARK-FIREFLIES) will have no effect on a simulation in progress.

But I'm not sure that's even true! It seems, for example, that `flashes-to-reset` and `cycle-length` _do_ have an effect while running.

I personally think that sliders generally _should_ have an effect on a running model: that's part of what makes NetLogo fun. But **Fireflies** is one of the "classic" NetLogo models, and we have to make really really sure that we don't break anything. In any case, I'll look into it...

**Comment by nicolaspayette** [comment]
It's been decided that, given the special status of the **Fireflies** model, its current behavior should be preserved. I have modified the text in the info tab so that it now correctly describes which widgets have an effect on a running simulation and which don't: 759b0c8.

I have also clarified the STRATEGY section a bit: a2ed326d45048bbace2f36feacf270da67612ff3.
