### ISSUE TITLE
There sort of is inheritance in Wealth Distribution

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#208]
The Info Tab says "There is no inheritance of wealth." and yet there is inheritance of land because offspring are located at the same place as their parent.

However if `move-to one-of patches with [not any? turtles-here]` is added to `set-initial-turtle-vars`

you get a much more equitable outcome.

I think the Info Tab should bring up this issue.

**Comment by nicolaspayette** [comment]
> I think the Info Tab should bring up this issue.

Agreed: c1cf50c.

(I noticed that the **Sugarscape 3 Wealth Distribution** model in the library _does_ have the `move-to one-of patches with [not any? turtles-here]` rule. But while the **Sugarscape** version aims to model a steady-state population where turtles are just re-used for efficiency, it seems that the "basic" **Wealth Distribution** model really considers new turtles to be the offspring of their parents, in which case it makes sense to have them be born in the same location.)

**Comment by SethTisue** [comment]
It's always confused me how Wealth Distribution _seems_ like a Sugarscape model, but isn't exactly. It's in the uncanny valley between Sugarscape and not-Sugarscape.

**Comment by nicolaspayette** [comment]
I share the uneasiness. It seems to me that, in general, library models that are almost-the-same-but-not-quite are a frequent source of confusion.
