### ISSUE TITLE
Heroes & Cowards says it is fixed in the info tab but it's not.

### ISSUE THREAD

**Issue by qiemem** [NetLogo/models#232]
This section of the info tab, I believe, only belongs in the version on the intro-to-abm website: https://github.com/NetLogo/models/blob/f44a36bb63be20c1d0c8e1e67bd6ceda0b5567cd/IABM%20Textbook/chapter%202/Heroes%20and%20Cowards.nlogo#L314-L318

The fix is most definitely not present (and should not be).

**Comment by nicolaspayette** [comment]
Looks like it was messed up in https://github.com/NetLogo/IABM-Models/commit/100f6bc23d263ede107639bbed9a4dfb40b8fd74, and I didn't remove the extra text when I cleaned it up in https://github.com/NetLogo/models/commit/32d8a38af3b06338a0beef5f072ced6dca35efdb. Those were hectic times. Anyway, thanks @qiemem: good catch!
