### ISSUE TITLE
5.2.0-RC4 model nitpicks

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#26]
* Models Library dialog: it's a little odd that "Alternative Visualizations" is the first thing under Sample Models. so for example there is code that sorts "unverified" to the end rather than in alphabetical order, maybe should do same here. AH: @nicolaspayette do you know how to do this? (NP: https://github.com/NetLogo/models/issues/32)
* Turtles Circling Simple has all-caps "SETUP" and "GO" buttons. AH: Done.
* DLA extensions -> DLA Extensions for consistency with the other chapter 3 folders. AH: Changed folder + legal.txt.
* Agentset Efficiency has no preview image. (@FrankDuncan says there are other models with this problem as well) AH: On it.
* Models Library dialog, IABM Models, chapter 8 folder: an empty "data" folder shows up. I think there might be code somewhere that allows directories like this to be excluded? AH: @nicolaspayette would you know how to do this? (NP: https://github.com/NetLogo/models/issues/33)
* Run Example info tab uses all caps for primitive names, it should use `typewriter font`. AH: Done.
* Run Example info tab has broken link for CC BY-NC-SA 3.0 logo, perhaps other models are affected too?
* Ticket Sales go button doesn't have the "Disable until ticks start" checkbox checked. (It wouldn't surprise me if this mistake were made in many of the new models; I'd suggest checking them all.) AH: done.
* Wolf Sheep Simple 2, "number-of-sheep" slider is positioned weirdly high. AH: done

**Comment by SethTisue** [comment]
Traffic Grid Goal's WHAT IS IT section begins with "This model is part of the textbook..."; inconsistently with the other models.

**Comment by SethTisue** [comment]
sometimes the alternative versions of a model have identical first-paragraph of their WHAT IS IT sections, so e.g. when I click on Traffic Basic Utility and Traffic Basic Adaptive in the Models Library, the text displayed is identical.

**Comment by SethTisue** [comment]
In the ACKNOWLEDGEMENT section of the textbook models, "Cambridge, Ma" should "Cambridge, MA"

**Comment by SethTisue** [comment]
There is a lot of general inconsistency about whether citation information is indented with a bullet or not. see e.g. the info tab of Fire Simple. The info tab contains a total of eight citations. Four are bulleted, four are not.

I suggest using the bullets because it calls the citation out as something most readers won't need to read.

**Comment by SethTisue** [comment]
must the ACKNOWLEDGEMENT repeat the name of the book twice, once regular, once as a citation?

isn't it enough to put the citation in HOW TO CITE?

**Comment by SethTisue** [comment]
Fire simple info tab uses double quotes for primitive names e.g. “neighbors4” , should be `typewriter font`

**Comment by SethTisue** [comment]
in general, Markdown is under-utilized in the info tabs of the new models. I think this is a hangover from the old days when NetLogo only supported plain text for this.

**Comment by SethTisue** [comment]
ACKNOWLEDGEMENT section of textbook models is inconsistent from model to model. for example some models have this text, others' don't: "This model is in the IABM Textbook folder of the NetLogo models library. The model, as well as any updates to the model, can also be found on the textbook website: http://intro-to-abm.com." (For example, Fire Simple doesn't.)

**Comment by SethTisue** [comment]
in chapter 8 models, all of the example models are in the form "Foo Example", but then instead of "HubNet Example", it's "Example HubNet"

**Comment by SethTisue** [comment]
Simple Viral Marketing's preview image is poor. This suggests that the new preview images should be reviewed not only for presence/absence, but also for whether the image is any good.

**Comment by nicolaspayette** [comment]
@arthurhjorth, if you need help with anything else on that list, just open a separate issue and assign me.

**Comment by arthurhjorth** [comment]
All these are either fixed, or have new issues for individual points, so closing now. Thanks so much for this list, @SethTisue
