### ISSUE TITLE
some models have multiple HOW TO CITE sections

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#27]
for example, Fire Simple has two; each is different

**Comment by arthurhjorth** [comment]
A lot of the 'simplified' or 'extension' models do - one is a reference to the model itself, one is a reference to the model that it extends, and/or the original model in the library. Uri and I talked a while ago about this, and that was what he wanted. (Including the Credits and References reference to the original model.)

**Comment by SethTisue** [comment]
if multiple citations are needed, surely all of them should nonetheless be collected into a single HOW TO CITE section? it's really confusing to have to

**Comment by arthurhjorth** [comment]
Oh, I see! @frankduncan or @nicolaspayette might need to add an exception about the textbook folder to the script that does that.

**Comment by frankduncan** [comment]
Should notarize just ignore the IABM directory?  Should there be any checking that says "hey, you need to have a HOW TO CITE" for all models?  Should there be extra checking for IABM stuff in general?

**Comment by arthurhjorth** [comment]
As far as I understand it still needs to add the "COPYRIGHT AND LICENSE" section, but because of the many different references to other models just skip the "How to cite" section. @UriCCL please confirm this (that book models are also released under CC BY-NC-SA 3.0)

**Comment by SethTisue** [comment]
not sure if it's the path you want to take on this, but I want to note that there is some existing precedent for a section to be part automatic, part manual — CREDITS AND REFERENCES works this way. you can include it manually, and then the automatic stuff gets added afterwards.

**Comment by nicolaspayette** [comment]
Fixed by https://github.com/NetLogo/models/commit/df2fee6345c338f0184c391cdcb9e2b7f49e0043#diff-dda7248f1df22258d6f2f3639c399792R146.
