### ISSUE TITLE
Reorganize Code Examples Folder

### ISSUE THREAD

**Issue by bainco** [NetLogo/models#273]
As per the 7/27 discussion with Uri, @arthurhjorth, and @bainco, the `Code Examples` folder needs to be reorganized.

Each extension will have its own folder in the `Code Examples` folder with code examples that use that extension being relocated into this new sub-folder.

For example, the `GoGoMonitor` and `GoGoMonitor Simple code` examples will now be located in the `Code Examples/gogo` folder.

This is an effort to standardize this folder in preparation for the introduction of LevelSpace code examples. Note that currently the Sound and GIS extensions have their own folders but other extensions do not.

Given the current code examples, this will necessitate creating the following folders:
1. gogo
2. gis
3. matrix
4. vid
5. palette
6. profiler
7. sound
8. table
9. bitmap
10. nw (in preparation for a future commit containing these examples)

The new Video Camera Example will have to be located in both bitmap and vid folders (at Uri's request).

**Comment by bainco** [comment]
Please see the 18fb38a of the `reorganize-code-examples` branch. It addresses these issues, minus having the new Video Camera Example in two folders. I wasn't sure what the correct way to do that was.

**Comment by bainco** [comment]
Travis build fails because the changed path name (`Code Examples/Sound` to `Code Examples/sound') and others (`vid` and `gis` need to be fixed in .gitignore). Should be an easy fix in PreviewImagesTest.scala

**Comment by nicolaspayette** [comment]
Looks good so far!

> The new Video Camera Example will have to be located in both bitmap and vid folders (at Uri's request).

Makes sense. To duplicate the model, you will have to edit:

https://github.com/NetLogo/NetLogo/blob/hexy/project/ModelCrossReference.scala

You should coordinate with @mrerrormessage for that one.

**Comment by bainco** [comment]
@nicolaspayette, what's the correct process for that? Do I modify the file and open up a pull request? Or do I just ask nicely?

**Comment by nicolaspayette** [comment]
> Do I modify the file and open up a pull request?

Yes.

> Or do I just ask nicely?

If you need help. :-) And if you're doing anything that involves significant changes to the NetLogo build, you should definitely check with him beforehand.

In this case, however, the modification to `ModelCrossReference.scala` should be pretty trivial. It can be tested by running `dist/modelCrossReference` from `sbt` (from the NetLogo root, not the `models` folder).

**Comment by bainco** [comment]
Hmm... well it says I don't have permission to edit the NetLogo repo.

**Comment by nicolaspayette** [comment]
You can fork it and submit a PR from your fork.

**Comment by bainco** [comment]
So we have a record of all discussions:

@nicolaspayette 
> I do have one question, however: have you guys considered the possibility of grouping all the extensions folders under a single Extensions Examples folder under Code Examples? Since Library folders are presented in alphabetical order, the extension folders end up being scattered all over the Code Examples folder (which is pretty big). There is nothing wrong with that per se, but it looks… untidy? All our Library folder names are capitalized and usually have relatively descriptive names. Having a folder just called vid, in lowercase, looks like a mistake. It’s also not very helpful if you don’t already know that vid is an extension. Grouping them all under an Extensions Examples folder would solve that problem by giving them context. And the lowercase names would now make sense.

Uri agreed
