### ISSUE TITLE
New Model(s): LevelSpace Code Examples

### ISSUE THREAD

**Issue by bainco** [NetLogo/models#277]
To be located in the `Code Examples/Extensions Examples/ls` folder.

At an earlier meeting, we discussed having 2 (possibly 3) examples:
1. An example showing how to open models in LevelSpace
2. An example with turtles, where each turtle has a child model associated with it (then in the `go` each turtle asks its model to `go`

**Comment by arthurhjorth** [comment]
Added two, will add one more. 

As *non-*Code Example models, @qiemem has the Brain model that we might want to add. I also *think* we should add our standard Climate Change - WSP model as an example of *interacting* models, but as Ex-Czar that isn't my decision. @bainco , what do you think? (I *think* we agreed that we would add them at themeeting with Uri, but I can't find my meeting notes. Sigh.)

**Comment by arthurhjorth** [comment]
Btw, even though I feel fairly confident I got them right, would someone please check them out? Happy to make changes. Cheers /a

**Comment by bainco** [comment]
> As non-Code Example models, @qiemem has the Brain model that we might want to add. I also think we should add our standard Climate Change - WSP model as an example of interacting models

I think those both would great models to add, especially since they demonstrate two different ways to use LS (and Kicked Rotators a third).

> I think we agreed that we would add them at themeeting with Uri

We never explicitly decided, however, we talked about both of these models and we came up with the naming scheme for adding LS models, so I think they should both be included.

**Comment by UriCCL** [comment]
I agree.

-- Uri

**Comment by bainco** [comment]
Should have closed with #283

**Comment by nicolaspayette** [comment]
> Should have closed with #283

Yeah, I think the GitHub autoclose doesn't work with issue titles: only commit messages.
