### ISSUE TITLE
bad bug in Communication-T-T Network Example

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#28]
the go button keeps stopping.

it's because in this code:

    if not all? turtles [ message? ] [ stop ]

the `not` should be removed.

**Comment by SethTisue** [comment]
also, the style guide says that "stop" checks like this should go at the top of the go procedure, not the bottom.

**Comment by arthurhjorth** [comment]
Fixed with ecd425686fbdcf8d84ac9681bc2fab0767c59f78
