### ISSUE TITLE
GenEvo2-4: Lame preview images

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/models#302]
Perhaps you're already aware of this and planning to take care of it before the official release of Hexy (in which case, please ignore me), but some of the new models have kind of lousy preview images.  In particular, I noticed this with the GenEvo models.  GenEvo 1 has a respectable preview image, but the rest are unimpressive.

Here's GenEvo 2:

![genevo 2](https://cloud.githubusercontent.com/assets/912890/18792367/d52f9350-817b-11e6-9645-f53e3bf55711.png)

Here's GenEvo 3, which has an image that is identical to GenEvo 2:

![genevo 3](https://cloud.githubusercontent.com/assets/912890/18792365/d527b518-817b-11e6-968b-0d7cedc0f2a3.png)

I'd say that, regardless of how this gets resolved, GenEvo 3 really ought to have a different image than GenEvo 2.  Particularly, I would recommend using an image that shows the aspects of GenEvo 3 that make it different from GenEvo 2.

Finally, here's GenEvo 4, which is tragically vapid:

![genevo 4](https://cloud.githubusercontent.com/assets/912890/18792366/d52877be-817b-11e6-868f-b7c28e77eba0.png)

I would suggest providing some custom preview commands (as detailed [here](https://github.com/NetLogo/NetLogo/wiki/Unofficial-features#preview-images)) to get the models to produce some more interesting visuals for the previews.

Note that I haven't thoroughly checked the preview images of the new models at all, so this same issue might apply to some other new models, as well.

**Comment by bainco** [comment]
Yeah, GenEvo's are just placeholders. We'll fix this in hexier.

**Comment by bainco** [comment]
@dsugat, you put any thought into this? I don't have any useful suggestions.
