### ISSUE TITLE
Move "Alternative Visualizations" folder to top level

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#32]
In, https://github.com/NetLogo/models/issues/26#issue-64752417 @SethTisue says:

> Models Library dialog: it's a little odd that "Alternative Visualizations" is the first thing under Sample Models. so for example there is code that sorts "unverified" to the end rather than in alphabetical order, maybe should do same here.

@UriCCL says:

> Regarding the Alt Viz folder, I think this folder should be outside of sample models entirely, just like curricular models.

The question of where it should go in the list is still open. I'm inclined to think it should just be added at the end.

**Comment by nicolaspayette** [comment]
@UriCCL confirms: at the end.

(And just to be entirely clear, that's at the end of the top level of the tree.)

**Comment by SethTisue** [comment]
fwiw, that was how we handled the Perspective Demos folder in NetLogo 4.1.

**Comment by nicolaspayette** [comment]
This can be close upon review/merge of https://github.com/NetLogo/NetLogo/pull/747 by @frankduncan.
