### ISSUE TITLE
Heroes and Cowards: preset configurations label too big

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#35]
Nathan writes:

> Bug in Heroes and Cowards -> the “preset configurations” label is too big and makes it so you can’t click the “dot” and “frozen” buttons.

**Comment by nicolaspayette** [comment]
Weirdly, this show up OK for me on Linux. The label _is_ too big, but it's also transparent, so I can see the buttons fine.

Could it be that label transparency is buggy on other platforms? Can folks with Macs or Windows machines confirm that?

(I'll make the label smaller in this particular model anyway.)

**Comment by nicolaspayette** [comment]
Oh, I see that @arthurhjorth took care of resizing the label in https://github.com/NetLogo/models/commit/d62ca588950deb08621b5bdc8018bf2a1802f60d.

**Comment by nicolaspayette** [comment]
Oh, I get it now: the buttons are visible but not clickable. No bugs, then. Closing.

**Comment by arthurhjorth** [comment]
Argh sorry yes, I should have tagged that in the commit message. APologies,
went a bit too fast there.
