### ISSUE TITLE
Break modelsim folder in two

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#36]
@mnovakccl says:

> Evolution:
- Bacteria Food Hunt
- Bacteria Hunt Speeds
>
> Population Bio:   
- Bug Hunt Disruptions
- Bug Hunt Environmental Changes
- Bug Hunt Predators and Invasive Species

**Comment by nicolaspayette** [comment]
@arthurhjorth: I moved the models and updated `legal.txt` to reflect the move. You can close the issue once you check that everything is OK.

**Comment by arthurhjorth** [comment]
Looks good, thanks!
