### ISSUE TITLE
Fish Tank Genetic Drift - Pen name casing

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/models#371]
In light of NetLogo/NetLogo#1542, we would like to see plot pen name casing fixed in Fish Tank Genetic Drift, which is to say that it isn't alright that the model has plots with pens named both "G" and "g", "F" and "f", "T" and "t", or, most abhorrently, "B" and "B".  Duplicate pen names should be forbidden, and "G" and "g" should be considered duplicate names.

**Comment by bainco** [comment]
Agreed. Technically, we don't have a standard in the style guide that dictates how plot pen names should be assigned. However, in the models library, the de facto standard is that capitalization in the code tab should be reserved for special cases (pun intended) only. Henceforth, plot pen names need to be lowercase.

**Comment by bainco** [comment]
As of 6a320a7, there are now two automated tests that catch this issue in Library models:

1. Ensure there are no plots with the same name under case insensitivity
2. Ensure there are no plot-pens (within a single plot) with the same name under case insensitivity
