### ISSUE TITLE
Problems with info tab and placement of Rock Paper Scissors

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#380]
The info tab has two sentences that need to be rewritten:

> Here, the occurrences of the events of are approximately independent since they’re being performed by different organisms.

Probably remove second 'of'

> Two random neighbors attempt to reproduce to each other.

How can one "reproduce to" another?

The model is under 'evolution' but I don't see the connection. There is no mention of evolution nor is evolution being modeled.

**Comment by LaCuneta** [comment]
Thanks for your comments on this and the other models, I'll check on getting them taken care of.

> The model is under 'evolution' but I don't see the connection. There is no mention of evolution nor is evolution being modeled.

This one I can answer, since i think it was already [moved](https://github.com/NetLogo/models/commit/35a02fd37a08017baed8601b2cc2c0d6dfec382c)

**Comment by UriCCL** [comment]
Thanx Ken. Much appreciated.

-- Uri
