### ISSUE TITLE
bug: Mouse Drag One Example is missing a call to `display`

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#382]
in the `go` procedure, after the call to `reset-perspective`, the model ought to also call `display`, otherwise the view doesn't update and the halo doesn't disappear when the user releases the mouse button

this came up at https://stackoverflow.com/questions/49708774/netlogo-5-2-hide-the-halo/49709637

**Comment by bainco** [comment]
Fixed in 91d464a
