### ISSUE TITLE
System Dynamics rolling plot

### ISSUE THREAD

**Issue by gerardoRolong** [NetLogo/models#389]
When plotting a Stock the code line: ```set-plot-x-range (ticks - 10) ticks``` doesn't seem to work at all I even tried in the wolf-sheep System Dynamics example and didn't work

**Comment by LaCuneta** [comment]
Thanks for your interest in NetLogo.

Have you tried turning off "Auto scale?" on your plot?  If it's on, it will supersede any range you set manually.

If you have further questions about writing NetLogo code, we recommend using the [NetLogo users group](
https://groups.google.com/d/forum/netlogo-users).  If you think you found a bug in the NetLogo application, you can report it at [the NetLogo repository](https://github.com/NetLogo/NetLogo).
