### ISSUE TITLE
Duplicate "Bug Hunt Predators and Invasive Species" models

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#39]
Our `"every model has a unique name"` unit test complains that there are two copies of **Bug Hunt Predators and Invasive Species**. We have a "one world" version in `BEAGLE Evolution`:

https://github.com/NetLogo/models/blob/master/Curricular%20Models/BEAGLE%20Evolution/Bug%20Hunt%20Predators%20and%20Invasive%20Species.nlogo

And a "two worlds" version in `ModelSim`:

https://github.com/NetLogo/models/blob/master/Curricular%20Models/ModelSim/Population%20Biology/Bug%20Hunt%20Predators%20and%20Invasive%20Species.nlogo

@UriCCL, @arthurhjorth, @mnovakccl... Should we rename one of the two? Or overwrite the one in BEAGLE?

(@frankduncan, just a heads up that you should be aware of this if you run the units tests.)

**Comment by mnovakccl** [comment]
I say we overwrite the one in BEAGLE with the two world version.    We need
to remove/replace the one world version from the library.    The old one
doesn't grant us any unique functionality.

On Sun, Mar 29, 2015 at 5:27 PM, Nicolas Payette <notifications@github.com>
wrote:

> Our "every model has a unique name" unit test complains that there are
> two copies of *Bug Hunt Predators and Invasive Species*. We have a "one
> world" version in BEAGLE Evolution:
>
>
> https://github.com/NetLogo/models/blob/master/Curricular%20Models/BEAGLE%20Evolution/Bug%20Hunt%20Predators%20and%20Invasive%20Species.nlogo
>
> And a "two worlds" version in ModelSim:
>
>
> https://github.com/NetLogo/models/blob/master/Curricular%20Models/ModelSim/Population%20Biology/Bug%20Hunt%20Predators%20and%20Invasive%20Species.nlogo
>
> @UriCCL <https://github.com/UriCCL>, @arthurhjorth
> <https://github.com/arthurhjorth>, @mnovakccl
> <https://github.com/mnovakccl>... Should we rename one of the two? Or
> overwrite the one in BEAGLE?
>
> (@frankduncan <https://github.com/frankduncan>, just a heads up that you
> should be aware of this if you run the units tests.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetLogo/models/issues/39>.
>



-- 
------------------------------------------------------------
Michael Novak, Instructor and
Instructional Materials Designer
Center for Connected Learning and Computer-Based Modeling
School of Education and Social Policy
Northwestern University
219 Annenberg Hall, 2120 N Campus Drive, Evanston IL 60208

**Comment by nicolaspayette** [comment]
@mnovakccl: I like that answer! The only tricky part is the credits and references. Should we combine the two by adding:

> This model is also a part of the BEAGLE curriculum (http://ccl.northwestern.edu/simevolution/beagle.shtml).

...to the ModelSim version's info tab?

(To be clear: the model would still appear under both folders, but it would be the exact same file copied in both places.)

**Comment by mnovakccl** [comment]
how about:

This is a 2 world view model that evolved from an earlier model of the same
name with a 1 world view, that was originally developed part of the BEAGLE
curriculum.

On Sun, Mar 29, 2015 at 6:02 PM, Nicolas Payette <notifications@github.com>
wrote:

> @mnovakccl <https://github.com/mnovakccl>: I like that answer! The only
> tricky part is the credits and references. Should we combine the two by
> adding:
>
> This model is also a part of the BEAGLE curriculum (
> http://ccl.northwestern.edu/simevolution/beagle.shtml).
>
> ...to the ModelSim version's info tab?
>
> (To be clear: the model would still appear under both folders, but it
> would be the exact same file copied in both places.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetLogo/models/issues/39#issuecomment-87493529>.
>



-- 
------------------------------------------------------------
Michael Novak, Instructor and
Instructional Materials Designer
Center for Connected Learning and Computer-Based Modeling
School of Education and Social Policy
Northwestern University
219 Annenberg Hall, 2120 N Campus Drive, Evanston IL 60208

**Comment by nicolaspayette** [comment]
Following email discussions, I added the "Two Regions" suffix to the name of the ModelSim version. If anyone has a better name to suggest, feel free to reopen the issue.
