### ISSUE TITLE
Markdown in IABM models

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/models#43]
Reported by @SethTisue:

"in general, Markdown is under-utilized in the info tabs of the new models. I think this is a hangover from the old days when NetLogo only supported plain text for this."

**Comment by nicolaspayette** [comment]
Closing this one. #67 helps, at least for the citation/copyright parts. The rest is something I'll keep an eye on and try to improve as I go along instead of an issue that can be resolved in one fell swoop.
