### ISSUE TITLE
Deal with preview images having non-square aspect ratios

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#48]
The models library dialog displays them as squares. If they're not, they're cropped, in sometimes awkward ways.

This mostly happens with manual previews, when they're done carelessly, but can also happen with automatic previews of models with non-square worlds (a point in case is **Simple Economy**, where I had to write custom preview commands using `resize-world`: https://github.com/NetLogo/models/commit/dc679793022b82b302fe8b4be62d339807949aee).

My own inclination would be to shrink the image to fit in the dialog instead of cropping it, but we could also conceivably write a script to catch non-square previews in the library. Certain models are certainly better off with custom previews than with shrunk images (e.g., again, **Simple Economy**).

In either case, implementing https://github.com/NetLogo/NetLogo/issues/760 could help.

**Comment by nicolaspayette** [comment]
Many NIELS models need manual previews because of that issue.

**Comment by SethTisue** [comment]
fwiw, this was very much a conscious choice, on aesthetic grounds. I found it distracting for the shape of the preview to change when browsing the models library in the app, and I found the resulting web pages less attractive, too.

you can definitely argue it the other way, I'm just sayin'.

perhaps it could be a setting in the model?

**Comment by nicolaspayette** [comment]
I very much agree with not changing the shape of the preview while browsing. What I propose is shrinking the image instead of cropping it. https://github.com/NetLogo/NetLogo/commit/48959de7b79e70ec050661f8a7c937aeb003f2ab (part of https://github.com/NetLogo/NetLogo/pull/886) adds [letterboxing](https://en.wikipedia.org/wiki/Letterboxing_%28filming%29)-style black bars to the images, thereby ensuring that no important part of the image is accidentally lost. It basically does automatically what the NIELS previews did manually. The few models for which it doesn't look good can still use custom or manual previews.

**Comment by SethTisue** [comment]
> What I propose is shrinking the image instead of cropping it

I understand. That is exactly what we originally considered and rejected. (Perhaps wrongly.)

**Comment by mrerrormessage** [comment]
I like the letterboxing solution. I think black is definitely the best color to letterbox in, as most models use it as the background color anyway. Perhaps if we run across a lot of models where it doesn't work well, we could consider adding an option to set the background color in the preview editor? I like this solution for now.

**Comment by nicolaspayette** [comment]
I will do a round before `hexy` and:

- [ ] write custom preview commands for any model that doesn't look good when letterboxed;
- [ ] get rid of manual preview images that were created to work around the cropping (only the NIELS models, I think)
