### ISSUE TITLE
Artificial anasazi doesn't load background

### ISSUE THREAD

**Issue by qiemem** [NetLogo/models#57]
I assume there's a missing file or something.

**Comment by nicolaspayette** [comment]
@qiemem, can you be more precise? It seems to work fine for me in the 5.2 release. Note that you can choose between multiple "map views". The default one is "water sources", which doesn't show much. Maybe it should be a different one...

**Comment by qiemem** [comment]
Oops, I'm an idiot. That was it. I just loaded it up, it wasn't what I expected, but didn't have time to investigate, so just logged an issue so it wouldn't get lost. Sorry about that!

**Comment by nicolaspayette** [comment]
>That was it.

No problem! It made me realize that "water sources" is a bad default. I changed it to "zones".

> just logged an issue so it wouldn't get lost

I approve of that behavior.
