### ISSUE TITLE
Make sure BehaviorSpace experiments in library models are relevant

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#62]
E.g., Lennard-Jones has an experiment named `experiment1` which has only one run and doesn't do much. It should not be there.

I'm not sure how to assess that experiments are "relevant" without checking them all out, but a good way to catch some bad ones would be to disallow experiments named `experiment*`. Experiments included in models should have meaningful names anyway.

**Comment by nicolaspayette** [comment]
One case I'm not sure about: K-Means. It has one experiment named `experiment`: https://github.com/NetLogo/models/blob/03f3bd812c8a43e5eb34c7f09eeb8d6c93a3ad9f/Sample%20Models/Computer%20Science/K-Means%20Clustering.nlogo#L678. @qiemem, @arthurhjorth: should it stay or should it go? If it stays what should it be named?

**Comment by nicolaspayette** [comment]
@qiemem, @arthurhjorth: ping?

**Comment by arthurhjorth** [comment]
So sorry, this flew under my radar.

No, it shouldn't be in there. Sorry it was there to begin with.

**Comment by nicolaspayette** [comment]
:+1: Thanks!
