### ISSUE TITLE
Fix Traffic Simple Adaptive

### ISSUE THREAD

**Issue by qiemem** [NetLogo/models#65]
This model has some serious bugs. I'm on the fix.

**Comment by nicolaspayette** [comment]
:+1:

**Comment by qiemem** [comment]
Note to self: Merge in any changes from repo version.

**Comment by nicolaspayette** [comment]
@qiemem, any estimated time of completion for that? No rush. Just curious.

**Comment by qiemem** [comment]
Today probably. I've merged the updates from master in and am working with Uri on improvements to the info tab right now.

**Comment by nicolaspayette** [comment]
Awesome! Open a PR when done?

**Comment by qiemem** [comment]
will do
