### ISSUE TITLE
"Myself Example" uses turtle buttons

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#72]
There is technically nothing wrong with that, but turtle buttons are rarely used in the library and their functioning may not be obvious to new users.

Since `myself` is an important and difficult thing to grasp for beginners, this example is probably consulted often. We should avoid having anything in it that could distract from its main point.

Unlike in Termites, turtle buttons serve no specific purpose in it.

Opinions welcome. Unless someone can point out a reason not to, I'll convert the turtle buttons to regular buttons.

**Comment by SethTisue** [comment]
+1
