### ISSUE TITLE
Runtime error in "4 Block Stalagmites"

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/models#75]
~~~
predicate is not a strictly-less-than or strictly-greater than relation
error while column-kid 0 running SORT-BY
  called by procedure ORGANIZE-COLUMN
  called by procedure ORGANIZE-RESULTS
  called by procedure GO-ORG
  called by Button 'Go-Org'
~~~

Here is the offending code:

~~~
to organize-column ; column-kids procedure
  let column-organizers sample-organizers with [ pxcor + 1 = [pxcor] of myself ]
  (foreach sort-by [ [ sample-summary-value ] of ?1 <=
                     [ sample-summary-value ] of ?2
                   ] [self] of column-organizers
           sort [ pycor ] of column-organizers
           [ ask ?1 [set ycor ?2] ])
end
~~~

To reproduce, click **Setup** and then **Go-Org**.

**Comment by nicolaspayette** [comment]
"4 Blocks Two Stalagmites" has the same problem.

**Comment by SethTisue** [comment]
recent versions of NetLogo are stricter about this, not because we changed something, but because recent JDKs are stricter. (I mean recent compared to when the ProbLab models were written, a decade or so ago.)

**Comment by nicolaspayette** [comment]
Ah, thanks for the info, Seth! I was surprised this hadn't been caught before. That explains it.

**Comment by SethTisue** [comment]
just one further note, typically the ProbLab models have manually generated previews, which means they don't get tested as part of the checksum based regression testing

**Comment by nicolaspayette** [comment]
@SethTisue: good thinking! That could very well have been the case, but I checked, and these particular models use the normal preview commands. The bug, however, only occurred when using `Go-org` instead of `go`, which explains why regression testing didn't catch it.

This situation may serve as a warning about why it's not a good idea to have multiple versions of `go`. It would have been better to have an `organized?` switch and to adjust `go`'s behavior accordingly. I'd rather not start making big changes to the ProLab models, however, so I'll leave them like this for now.
