### ISSUE TITLE
Typo in "Urban Suite - Tijuana Bordertowns model"

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/models#77]
"INIT-DENSITY determines the initial number of migrants at the stat of a model run."

stat should be start

**Comment by nicolaspayette** [comment]
Thanks for reporting, Ken! I recently automated the running of our spell-checking script (https://github.com/NetLogo/models/pull/64), so you should see fewer mistakes in the future. But it doesn't catch everything; human eyes like yours are invaluable!
