### ISSUE TITLE
All go buttons should have "Disable until ticks start"

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/models#81]
We still have lots of models that don't make use of the "Disable until ticks start" checkbox to prevent users from pressing "go" before "setup".

**Comment by nicolaspayette** [comment]
Agreed. I've been wondering for some time about how to automate testing for this.

I expect that a simple rule like "anything not named `"setup.*"` should be disabled until ticks start" will be too crude.

Maybe something like "everything named `"go.*"` should be disabled until ticks start" would be good enough? It wouldn't catch everything, but it would at least ensure that the model author has thought about the issue.

I'm not opposed to doing more sophisticated parsing either, but I'm afraid it could get tricky.

Open to suggestions, as always.
