### ISSUE TITLE
The first note in Ask Ordering Example is cut off

### ISSUE THREAD

**Issue by Idloj** [NetLogo/models#82]
The last word is missing

**Comment by nicolaspayette** [comment]
Thanks for reporting, @Idloj. Are you on Linux too? The default font on Linux is a bit wider, and most of our model authors are working on Mac or Windows, so we have _lots_ of models with labels cut off on Linux. I fix them when I see them, but I haven't been systematic about it yet. I will one day. In the meanwhile, reports like this are much appreciated. Thanks!

**Comment by Idloj** [comment]
Yes, I am on Linux (good choice)
