### ISSUE TITLE
The arrow in Info Tab Example is Mac specific

### ISSUE THREAD

**Issue by Idloj** [NetLogo/models#83]
In every other OS the tabs are aligned to the left. So it it just better without anything on the View.

**Comment by nicolaspayette** [comment]
I agree that it looks weird on Linux (and probably Windows too):

![screenshot from 2015-07-06 16 17 13](https://cloud.githubusercontent.com/assets/908754/8532203/86b24b6c-23fa-11e5-88ba-ee7c0eea595e.png)

Just getting rid of the giant red arrow may be a solution, but I wonder if we can do better. Any ideas?

**Comment by Idloj** [comment]
Why not just hiding the view, like in the GOGOs models?

**Comment by SethTisue** [comment]
sigh, another failed attempt to be clever (I think this one was mine)
